### ISSUE TITLE
Coding questions of HW5

### ISSUE THREAD

**Issue by Derick317** [ryeii/CS170#1]
Hi, I am a student who is self-studying this course online. I have a question about coding questions about SCC in homework 5. In the DFS section, the AG uses `explore` to find all vertices in the sink SCC. However, I don't think it is correct, for even if u is reachable from v, u and v are not necessarily in the same SCC.

**Comment by Derick317** [comment]
Maybe I need specify my question. The initial code considers that the last node is in the sink SCC, but it may not.
```
scc = explore(nx.to_dict_of_lists(random_graph), len(random_graph.nodes) - 1)
```

**Comment by ryeii** [comment]
Hey Deming, great question! 

Generally, it is true that for nodes u and v, v being reachable from u does not imply v and u belong to the same SCC. However, using explore in this particular case (HW5) is reasonable because ```random_graph``` is set up such that there exists a "sink SCC" where all nodes belong to it are in the same SCC, and all nodes outside of this SCC are unreachable from the said SCC (since it is the sink). You can find a text block above the question that explains how ```random_scc_graph()``` works.

"Below is a Graph with iconic SCC generator. It generates 4 possibly strongly connected components ABCD, then add edge AB, AC and BD, CD."

In this case, D is the "sink SCC," and node ```len(random_graph.nodes) - 1``` is guaranteed to be in D because D is the last SCC generated.

Though there are cases which there exists some nodes that are reachable but not strongly connected with sink, I think they are rare enough for a homework problem (where you can always regenerate the random graph). If you happened to run into one of these rare cases, try re-run the code block and generate a new graph should solve the issue :)

**Comment by Derick317** [comment]
Hi, Ryan, thanks for your reply!

From the definition of `random_scc_graph()` we know each of the four "SCC" is generated as a Erdős–Rényi graph, where each edge is included in the graph with probability _p_. So, there is a chance that some vertex is "isolated" because no edge is directed from it or no edge is directed to it.

Actually, I just want to make sure it's not because of my wrong coding, since I cannot contact with the staff ⊙ω⊙
